#pragma once


#define BLOXY_MOUSE_BUTTON_1         0
#define BLOXY_MOUSE_BUTTON_2         1
#define BLOXY_MOUSE_BUTTON_3         2
#define BLOXY_MOUSE_BUTTON_4         3
#define BLOXY_MOUSE_BUTTON_5         4
#define BLOXY_MOUSE_BUTTON_6         5
#define BLOXY_MOUSE_BUTTON_7         6
#define BLOXY_MOUSE_BUTTON_8         7
#define BLOXY_MOUSE_BUTTON_LAST      BLOXY_MOUSE_BUTTON_8
#define BLOXY_MOUSE_BUTTON_LEFT      BLOXY_MOUSE_BUTTON_1
#define BLOXY_MOUSE_BUTTON_RIGHT     BLOXY_MOUSE_BUTTON_2
#define BLOXY_MOUSE_BUTTON_MIDDLE    BLOXY_MOUSE_BUTTON_3